/**
 * This code was generated by Builder.io
 */
import React from "react";

function CafeHeader() {
  return (
    <section className="flex flex-col items-start px-4 w-full text-zinc-800 max-md:max-w-full">
      <div className="flex gap-5 justify-between self-stretch text-3xl max-md:max-w-full">
        <h1>Hennings Cafe</h1>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/91f7a91c4596b3add73c77be143dc9c1c3abc4bd8288fe7e388a56c8a217fcdd?placeholderIfAbsent=true&apiKey=62cc1c00d0454fed8ec6b8f31dfdb7b5"
          alt=""
          className="object-contain shrink-0 my-auto aspect-[1.17] w-[27px]"
        />
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/7d102aff1b6d345182f555c83273a6f4572077e0145518251aa2a399350511b0?placeholderIfAbsent=true&apiKey=62cc1c00d0454fed8ec6b8f31dfdb7b5"
        alt="Rating stars"
        className="object-contain mt-4 max-w-full rounded-sm aspect-[5.03] w-[146px]"
      />
      <p className="mt-2.5 text-base">Cafe</p>
    </section>
  );
}

export default CafeHeader;
