/**
 * This code was generated by Builder.io
 */
import React from "react";

const ratingCategories = [
  { name: "Outlets", id: "outlets" },
  { name: "Quietness", id: "quietness" },
  { name: "Atmosphere", id: "atmosphere" },
  { name: "Seating availability", id: "seatingAvailability" },
  { name: "Accessibility", id: "accessibility" },
];

const ratingImages = [
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/276df476672b1931b3478009f6d1f6dbb5bc787e82d9f4848fa4535530327851?placeholderIfAbsent=true&apiKey=62cc1c00d0454fed8ec6b8f31dfdb7b5",
    alt: "Rating for Outlets",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/c682c8e1ca23224c5c611b10ea16bede8e6a99e586d2b87037aa4000b5afa2d8?placeholderIfAbsent=true&apiKey=62cc1c00d0454fed8ec6b8f31dfdb7b5",
    alt: "Rating for Quietness",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/b6da11bab6638ba43ed6e249022187191e913c4134e81aa43343e2eeadebd62e?placeholderIfAbsent=true&apiKey=62cc1c00d0454fed8ec6b8f31dfdb7b5",
    alt: "Rating for Atmosphere",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/19cca96da184a2af9f4cd37159c39d3f12abbdb4b7da13fd4bd399fe1ed469ea?placeholderIfAbsent=true&apiKey=62cc1c00d0454fed8ec6b8f31dfdb7b5",
    alt: "Rating for Seating availability",
  },
];

function RatingSection() {
  return (
    <section className="flex flex-col px-3 mt-5 w-full max-md:pr-5 max-md:max-w-full">
      <div className="w-full max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[68%] max-md:ml-0 max-md:w-full">
            <div className="flex grow gap-1.5 mt-1 text-zinc-800 max-md:mt-10">
              <div className="flex flex-col items-start text-base">
                {ratingCategories.map((category) => (
                  <div
                    key={category.id}
                    id={category.id}
                    className={
                      category.id === "accessibility" ? "mt-5" : "mt-6"
                    }
                  >
                    {category.name}
                  </div>
                ))}
                <div className="self-stretch px-1 py-1 mt-2 text-xs rounded-lg bg-stone-200 shadow-[-1px_1px_2px_rgba(0,0,0,0.25)]">
                  Wheelchair accessible bathroom
                </div>
              </div>
              <div className="self-end px-1.5 py-1 mt-48 text-xs rounded-lg bg-stone-200 shadow-[-1px_1px_2px_rgba(0,0,0,0.25)] max-md:mt-10">
                Wheelchair accessible bathroom
              </div>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[32%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col max-md:mt-9">
              {ratingImages.map((image, index) => (
                <img
                  key={index}
                  loading="lazy"
                  src={image.src}
                  alt={image.alt}
                  className={`object-contain ${
                    index > 0 ? "mt-4" : ""
                  } rounded-sm aspect-[5.08] w-[132px]`}
                />
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default RatingSection;
