/**
 * This code was generated by Builder.io
 */
import React from "react";

function ReviewSection() {
  return (
    <section className="flex gap-5 self-start mt-12 text-base text-zinc-800 max-md:mt-10">
      <img
        src="placeholder.jpg"
        alt=""
        className="flex shrink-0 rounded-full bg-zinc-300 h-[50px] w-[50px]"
      />
      <div className="flex flex-col grow shrink-0 my-auto basis-0 w-fit">
        <h2 className="self-start font-bold">Tired student</h2>
        <p className="mt-2">Sat here and worked on a hackathon for 12 hours!</p>
      </div>
    </section>
  );
}

export default ReviewSection;
