/**
 * This code was generated by Builder.io
 */
import React from "react";

function ImageComponent({ src, alt, className }) {
  return <img src={src} alt={alt} className={className} loading="lazy" />;
}

export default ImageComponent;
