/**
 * This code was generated by Builder.io
 */

import React from "react";

function SearchIcon() {
  return (
    <button type="submit" aria-label="Submit search">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/28d145478f49fb2d75827ef185343b68f6bbbed14d4d4f977d12315e9db83d23?placeholderIfAbsent=true&apiKey=62cc1c00d0454fed8ec6b8f31dfdb7b5"
        className="object-contain shrink-0 aspect-[0.96] w-[25px]"
        alt=""
      />
    </button>
  );
}

export default SearchIcon;
