/**
 * This code was generated by Builder.io
 */
import React from "react";

const accessibilityOptions = [
  { label: "Wheelchair accessible entrance", selected: false },
  { label: "Wheelchair accessible bathroom", selected: true },
  { label: "Handicap parking", selected: true },
  { label: "Wheelchair accessible seating", selected: false },
  { label: "Elevators", selected: false },
];

function AccessibilitySection() {
  return (
    <section>
      <h2 className="mt-12 text-3xl text-zinc-800 max-md:mt-10">
        Was it accessible?
      </h2>
      <p className="text-xl text-slate-400">(Select all that apply)</p>
      <div className="flex flex-wrap gap-2.5 mt-6 text-xl text-zinc-800">
        {accessibilityOptions.map((option, index) => (
          <button
            key={index}
            className={`grow px-1.5 py-2 rounded-2xl ${
              option.selected
                ? "border-2 border-solid bg-slate-300 border-slate-400"
                : "bg-stone-200"
            } shadow-[-2px_2px_4px_rgba(0,0,0,0.25)] w-fit`}
          >
            {option.label}
          </button>
        ))}
      </div>
    </section>
  );
}

export default AccessibilitySection;
