/**
 * This code was generated by Builder.io
 */
import React from "react";

function CommentSection() {
  return (
    <section className="w-full">
      <label
        htmlFor="additionalComments"
        className="mt-10 text-xl text-black max-md:mt-10 max-md:ml-1.5"
      >
        Additional Comments:
      </label>
      <textarea
        id="additionalComments"
        className="flex shrink-0 mt-2.5 w-full rounded-2xl bg-stone-200 h-[269px]"
        aria-label="Additional Comments"
      />
    </section>
  );
}

export default CommentSection;
