/**
 * This code was generated by Builder.io
 */
import React from "react";

const limitations = ["No free Wi-Fi", "Laptop free", "Time limit"];

function LimitationsSection() {
  return (
    <section>
      <h2 className="mt-10 text-3xl text-zinc-800 max-md:mt-10">
        Any limitations?
      </h2>
      <p className="text-xl text-slate-400">(Select all that apply)</p>
      <div className="flex gap-2 mt-6 text-xl text-zinc-800">
        {limitations.map((limitation, index) => (
          <button
            key={index}
            className="px-2 py-2 rounded-2xl bg-stone-200 shadow-[-2px_2px_4px_rgba(0,0,0,0.25)]"
          >
            {limitation}
          </button>
        ))}
      </div>
    </section>
  );
}

export default LimitationsSection;
