/**
 * This code was generated by Builder.io
 */
import React from "react";

function PhotoUpload() {
  return (
    <section className="w-full">
      <div className="flex gap-4 mt-10">
        <h2 className="grow text-3xl text-zinc-800">Upload Photos:</h2>
        <button className="flex gap-3.5 self-start px-5 py-1.5 text-xl text-gray-600 rounded-2xl bg-stone-200 shadow-[-2px_2px_4px_rgba(113,153,167,1)]">
          Add files
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a47a3c31f3ff96458740be9f81affd369b178417d67fc9a56c98740c44406b25?apiKey=62cc1c00d0454fed8ec6b8f31dfdb7b5&"
            alt=""
            className="object-contain shrink-0 aspect-[1.04] w-[26px]"
          />
        </button>
      </div>
    </section>
  );
}

export default PhotoUpload;
