/**
 * This code was generated by Builder.io
 */
import React from "react";
import star from "../../assets/star.svg";
const ratingItems = [
  { label: "Outlets", id: "outlets" },
  { label: "Quietness", id: "quietness" },
  { label: "Atmosphere", id: "atmosphere" },
  { label: "Seating availability", id: "seating" },
];

function RatingSection() {
  return (
    <section className="self-stretch max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col items-start text-3xl text-zinc-800 max-md:mt-10">
            {ratingItems.map((item) => (
              <div
                key={item.id}
                className={`mt-14 max-md:mt-10 ${
                  item.id === "outlets" ? "mt-10" : ""
                }`}
              >
                {item.label}
              </div>
            ))}
          </div>
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow items-start mt-2.5 max-md:mt-10">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/6fcf08a1bffd234738ffc4e6527d6bbe4cdcf77f0df1007e7ccca4a41ca95ee3?apiKey=62cc1c00d0454fed8ec6b8f31dfdb7b5&"
              alt=""
              className="object-contain self-end aspect-square w-[29px]"
            />
            {[2, 3, 4, 5].map((num) => (
              <img
                key={num}
                src={star}
                alt=""
                className="object-contain mt-9 rounded aspect-[4.98] w-[293px]"
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

export default RatingSection;
