/**
 * This code was generated by Builder.io
 */
import React from "react";
import RatingSection from "./RatingSection";
import AccessibilitySection from "./AccessibilitySection";
import LimitationsSection from "./LimitationsSection";
import CommentSection from "./CommentSection";
import PhotoUpload from "./PhotoUpload";

function ReviewPage() {
  return (
    <main className="flex overflow-hidden flex-col items-start px-12 py-11 bg-stone-200 max-w-[800px] max-md:px-5">
      <h1 className="self-stretch text-4xl text-zinc-800">Leave a Review</h1>
      <RatingSection />
      <AccessibilitySection />
      <LimitationsSection />
      <CommentSection />
      <PhotoUpload />
      <button className="self-end px-9 py-3 mt-6 text-xl whitespace-nowrap rounded-2xl border-2 border-solid bg-slate-300 border-slate-400 shadow-[-2px_2px_4px_rgba(0,0,0,0.25)] max-md:px-5 max-md:mr-2.5">
        Share
      </button>
    </main>
  );
}

export default ReviewPage;
