/**
 * This code was generated by Builder.io
 */
import React from "react";

function ImageContainer({ src, alt, className }) {
  return <img src={src} alt={alt} loading="lazy" className={className} />;
}

export default ImageContainer;
