/**
 * This code was generated by Builder.io
 */
import React from "react";

function TagButton({ text, className }) {
  return (
    <span
      className={`px-1 py-1 whitespace-nowrap rounded-lg shadow-[-1px_1px_2px_rgba(0,0,0,0.25)] ${className}`}
    >
      {text}
    </span>
  );
}

export default TagButton;
